### ISSUE TITLE
点击导入115数据一直读图，根本进不去呀，求老哥解决

### ISSUE THREAD

**Issue by lcq224** [SingleVrUser/Display#1]
`读图的时候点开始也会闪退，但是这根本导入不了呀，哭了

**Comment by SingleVrUser** [comment]
读图？
![1](https://user-images.githubusercontent.com/110682484/183255768-311285f8-e032-41e2-b470-f3e291afab34.png)
（-图1）
是点击这里的开始后立即闪退吗？
![2](https://user-images.githubusercontent.com/110682484/183255789-06e1d7df-4c21-4591-8cb8-da10189a5a65.png)
（-图2）
那有没有显示这个对话框

**Comment by lcq224** [comment]
![屏幕截图(5)](https://user-images.githubusercontent.com/52266307/183256022-69b00dc2-62f7-4528-b01e-49ce7b46a4ed.png)
就这样一直读图，哭了

**Comment by SingleVrUser** [comment]
其他-浏览器，也是什么都没显示，一直读图吗？

**Comment by lcq224** [comment]
不是，这里有显示

**Comment by lcq224** [comment]
![屏幕截图(7)](https://user-images.githubusercontent.com/52266307/183272516-74bc5e0d-8ce1-469c-a54f-79f7ef079595.png)

**Comment by lcq224** [comment]
好了已经解决了，谢谢老哥，我把问题关了吧
