### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by zhichaoyes** [SingleVrUser/Display#2]
这个软件很厉害，辛苦了老哥
我电脑是 win11专业版
导入115数据只能导入基础的”云下载“文件夹。 尝试导入其他文件夹会闪退。
搜刮的时候匹配文件完成之后修改规则会闪退。
还有导入数据的时候点开搜刮就会闪退。

**Comment by SingleVrUser** [comment]
惊了，这么多BUG。
顺便问一下，你用的是哪一个版本的，我好找BUG

**Comment by zhichaoyes** [comment]
> 惊了，这么多BUG。 顺便问一下，你用的是哪一个版本的，我好找BUG

      我更新了1.5版本。之前的bug应该是第一次导入的时候可以多选几个文件夹，但是之后想导入其他文件夹就会闪退。更新之后可以多次导入其他文件夹了。
      另外，如果这次导入了全部的文件夹，日后网盘里新增的内容如果我再次导入它会不会重复扫描？我的网盘内容大概130T，导入时间23小时，不过这问题不大，我可以在网盘里提前建好文件夹将新下载的片存放起来。
      另外还有，如果导入或者搜刮中途中断了，重新导入就会出现类似30000/50000 就完成的bug，会不会导致他扫入的内容不全？不知是他默认续传了还是直接跳过了。
      还有一个闪退是我点开搜刮之后，不管我有没有在里面操作，只要关闭搜刮窗口，100%闪退，可能是因为文件夹里的内容太多导致数据库卡崩溃了？
      **目前问题最大的**就是搜刮的时候匹配文件完成之后有的片子我想 添加/修改 规则标签，比如立花里子。ddk等默认规则里没有的番号，不管是添加/修改中文还是字母添加/修改了点了保存就闪退。再打开也没有保存上。或许可以在设置--搜刮方式里添加个可以添加和修改自定义标签的功能？因为有些D  T 这样的单字母会搜刮到一些乱七八糟的封面。
     另外就是一些古早资源可能不包含 HXXX-123 这种番号格式,大概就是主角姓名这种。还有一些杂七杂八的国产资源能否让我自行归类。 比如说我新建个国产或者其他标签，自己把网盘里扫到的国产内容添加进这个标签里？
  以上是目前发现的bug，望修复。感谢作者，辛苦了

**Comment by zhichaoyes** [comment]
我更新了1.5版本。之前的bug应该是第一次导入的时候可以多选几个文件夹，但是之后想导入其他文件夹就会闪退。更新之后可以多次导入其他文件夹了。
  另外，如果这次导入了全部的文件夹，日后网盘里新增的内容如果我再次导入它会不会重复扫描？我的网盘内容大概130T，导入时间23小时，不过这问题不大，我可以在网盘里提前建好文件夹将新下载的片存放起来。
  另外还有，如果导入或者搜刮中途中断了，重新导入就会出现类似30000/50000 就完成的bug，会不会导致他扫入的内容不全？不知是他默认续传了还是直接跳过了。
  还有一个闪退是我点开搜刮之后，不管我有没有在里面操作，只要关闭搜刮窗口，100%闪退，可能是因为文件夹里的内容太多导致数据库卡崩溃了？
  **目前问题最大的**就是搜刮的时候匹配文件完成之后有的片子我想 添加/修改 规则标签，比如立花里子。ddk等默认规则里没有的番号，不管是添加/修改中文还是字母添加/修改了点了保存就闪退。再打开也没有保存上。或许可以在设置--搜刮方式里添加个可以添加和修改自定义标签的功能？因为有些D  T 这样的单字母会搜刮到一些乱七八糟的封面。
 另外就是一些古早资源可能不包含 HXXX-123 这种番号格式,大概就是主角姓名这种。还有一些杂七杂八的国产资源能否让我自行归类。 比如说我新建个国产或者其他标签，自己把网盘里扫到的国产内容添加进这个标签里？

**Comment by SingleVrUser** [comment]
1. 导入115数据时，如果选择的文件夹（包括子文件夹）的修改时间与数据库相同，应用会跳过该文件夹的。搜刮信息类似，也会跳过之前搜刮过的番号，但之前搜刮无结果的（未存入数据库的番号）还是会尝试再搜刮一遍信息。
2. 导入或者搜刮中途中断？是指没导入/搜刮完成就退出了整个应用，还是单纯关闭了导入/搜刮窗口。如果是前者，那导入115数据时的那个BUG我找到了，计划下一个版本修复（扫入的内容不全，下一版本会给选项选择“是否跳过已存在文件夹（修改时间一致）”，建议在更新下一版本后的第一次导入时不跳过），搜刮信息时我无法复现该现象😥。（PS:如果只是单纯关了窗口，导入/搜刮进程还会在后台继续运行，同样在下一版本中实现关闭窗口时自动退出当前未完成进程）
3. 搜刮信息时，你看左边显示的 根目录下的 “文件夹” 以及右边显示的 “文件夹和文件” ，这两个多不多。如果初始显示的数量都不多的话（不考虑未显示 或者说折叠 的文件夹），而且打开搜刮信息窗口后在什么都没操作的情况下关闭窗口时崩溃，那可能是因为其他原因崩溃的。
4. 设置-搜刮方式，这个我弄到一半就没弄了，同样在一下版本中完善😀。匹配文件完成后修改规则标签应用闪退的问题，修改/添加 我都操作过了，一切正常，暂时复现不了
5. 针对杂七杂八的番号和国产资源，我暂时没有很好的自动化方案。仅靠文件名无法获取

**Comment by zhichaoyes** [comment]
我不会编译这软件，可以帮我编译个新版本吗。或者告诉我如何自己编译？谢谢

**Comment by SingleVrUser** [comment]
> 我不会编译这软件，可以帮我编译个新版本吗。或者告诉我如何自己编译？谢谢

目前我还没有弄好，等我弄好了再发布编译好的新版本😀
如果你想学怎么编译的话，参照这个下面的链接就行
[创建第一个 WinUI 3项目](https://docs.microsoft.com/zh-cn/windows/apps/winui/winui3/create-your-first-winui3-app)

**Comment by zhichaoyes** [comment]
有编译好的新版本吗 发布一个

**Comment by SingleVrUser** [comment]
> 

已发布

**Comment by SingleVrUser** [comment]
> 有编译好的新版本吗 发布一个

已发布
