### ISSUE TITLE
扫码登录不成功

### ISSUE THREAD

**Issue by squallnk** [SingleVrUser/Display#3]
115登录用手机扫码登录 提示几秒后跳转然后 就回到扫码界面，操作系统win10 ,还有登录界面用cookie登录 一直显示 cookie无效，请重新登录 ，应该怎么获取？ 用editthiscookie倒出粘贴什么都没有

**Comment by SingleVrUser** [comment]
![QQ截图20220815120933](https://user-images.githubusercontent.com/110682484/184575914-ffc83e99-5b36-4959-b091-a569e6575bf1.png)
…
![QQ截图20220815121439](https://user-images.githubusercontent.com/110682484/184576063-401e9c14-00c2-452d-aea0-dcfde57f53be.png)

Cookie在浏览器里可以获取到
Cookie的格式类似：115_lang=zh；USERSESSIONID=xxx; SEID=xxx; …

**Comment by SingleVrUser** [comment]
扫码登录的BUG我待会看看
额外说明一下，“设置”-“115”-“导出”按钮，导出的是 editthiscookie 类浏览器插件通用的格式。
（在该应用中扫码登录，之前浏览器登录的账号会自动登出，而“导出”功能，可以在浏览器中用 “editthiscookie” 快速重新登录
