### ISSUE TITLE
显示方块

### ISSUE THREAD

**Issue by squallnk** [SingleVrUser/Display#48]
![Snipaste_2023-03-04_00-56-57](https://user-images.githubusercontent.com/40011596/222780769-82806e52-c3e2-4a9e-9b18-57eb2628d9ca.jpg)
这个显示方块是什么问题？我是win10系统。

**Comment by guxinshamo** [comment]
更新到v0.1.16.6后，我这也是图标变成了方块，之前正常显示。

**Comment by SingleVrUser** [comment]
> ![Snipaste_2023-03-04_00-56-57](https://user-images.githubusercontent.com/40011596/222780769-82806e52-c3e2-4a9e-9b18-57eb2628d9ca.jpg) 这个显示方块是什么问题？我是win10系统。

字体问题？难道是字体没安装，用的[Segoe Fluent Icons](https://aka.ms/SegoeFluentIcons)，一直用的这个v0.1.16.6也没换，装一下试试。
介绍：
https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font
下载地址：
https://aka.ms/SegoeFluentIcons

**Comment by SingleVrUser** [comment]
> 更新到v0.1.16.6后，我这也是图标变成了方块，之前正常显示。
装[Segoe Fluent Icons](https://aka.ms/SegoeFluentIcons)后再看看

**Comment by guxinshamo** [comment]
装Segoe Fluent Icons字体后，提示替换，安装后显示正常了。

**Comment by squallnk** [comment]
> > 更新到v0.1.16.6后，我这也是图标变成了方块，之前正常显示。
> 
> 装[Segoe Fluent Icons](https://aka.ms/SegoeFluentIcons)后再看
好了，缺少字体
