### ISSUE TITLE
cookie登录失败

### ISSUE THREAD

**Issue by PhoenixZhong** [SingleVrUser/Display#5]
cookie登录 ，输入后（点检查显示有七个键值），点提交提示说cookie无效，请重新输入。请问是cookie获取错误吗？

**Comment by PhoenixZhong** [comment]
网络异常，检查115登录状态时出现异常：由于目标计算机积极拒绝，无法连接。（127.0.0……数字地址）

**Comment by SingleVrUser** [comment]
检查一下“其他”-“浏览器”能否正常显示

**Comment by SingleVrUser** [comment]
> 网络异常，检查115登录状态时出现异常：由于目标计算机积极拒绝，无法连接。（127.0.0……数字地址）

看样子是网络问题

**Comment by PhoenixZhong** [comment]
> 

谢谢，在其他—浏览器，显示已经登录。但是好奇怪为什么会软件登录不了。一开始挂了代理登录，然后退出代理再登录的。都不行

**Comment by SingleVrUser** [comment]
如果显示已登录，那说明应用已经保存了Cookie。或许是因为网络不稳定吧😂。目前只有 “导入115数据”和 “播放视频”需要用到Cookie，如果这两个有问题你再通知我😁

**Comment by PhoenixZhong** [comment]
> 

谢谢
