### ISSUE TITLE
我导入证书了，还是不让安装。

### ISSUE THREAD

**Issue by guxinshamo** [SingleVrUser/Display#63]
重新安装了win11，但是我导入证书了，还是不让安装Display，以前没发生过这种现象。怎样绕过这个安装呢。

**Comment by guxinshamo** [comment]
改日期到2022年就可以了

**Comment by SingleVrUser** [comment]
> 重新安装了win11，但是我导入证书了，还是不让安装Display，以前没发生过这种现象。怎样绕过这个安装呢。

之前的证书8月份过期了
[v0.1.16.17](https://github.com/SingleVrUser/Display/releases/tag/v0.1.16.17)更新了证书，有效期到明年9月21号
