### ISSUE TITLE
前来支持一波！！！

### ISSUE THREAD

**Issue by killknight2022** [SingleVrUser/Display#7]
大佬牛逼！！！
然后大佬有没有想过搜刮信息和115的fid关联啊，每次重新扫很奇怪。
还有115本身还有标签功能，可以考虑一下把批量添加标签的接口做上去。
本人以前用python写过一个115批管理的东西，太烦了，没有继续，看到大佬的项目很开心。。。前来支持

**Comment by SingleVrUser** [comment]
搜刮信息和115的fid关联?是说关联一个文件夹，然后自动检查这个文件夹有没有更新吗
批量添加标签的功能 下个版本安排上

**Comment by SingleVrUser** [comment]
搜刮信息和115的fid关联?是说直接使用115的fid搜刮视频信息吗？这个我到后面会整合这两个步骤的（n个版本后吧😋）
批量添加标签的功能 下个版本安排上

**Comment by killknight2022** [comment]
不是啊，fid是115接口定义的file_id，就这个玩意，{fid: "2143436415849189005", uid: 343895934, aid: 1, cid: "2143185505151601888"}。关联之后就不必每次搜刮都从头开始吧，而且你存了之后，后续相关115的接口都会用得到。

**Comment by killknight2022** [comment]
然后还有你那个匹配文件名，emmmm，刚开始好像效率不是很高的样子，增添规则之后好像还行。你如果缺个番号标准化的，我可以提供一个老哥的项目，正则写得很详细，拿来用岂不美哉。

**Comment by killknight2022** [comment]
https://github.com/Yuukiy/JavSP这是一个本地刮削的，https://github.com/Yuukiy/JavSP/blob/master/core/avid.py这位老哥辛苦整的正则。(手动狗头)

**Comment by SingleVrUser** [comment]
> 每次搜刮都从头开始
我再重新理解一下。搜刮信息和115的fid“关联”，再次搜刮的时候会跳过已关联的fid。这样理解对吗

**Comment by killknight2022** [comment]
对啊，可以直接跳过，没有必要再刮一次了吧，当然这样做，还要开放一个可以重新刮的功能，但是实现也很简单一个判断搞定。

**Comment by SingleVrUser** [comment]
目前已经根据“番号名”跳过已搜刮的信息了

**Comment by SingleVrUser** [comment]
> [https://github.com/Yuukiy/JavSP这是一个本地刮削的，https://github.com/Yuukiy/JavSP/blob/master/core/avid.py这位老哥辛苦整的正则。(手动狗头)](https://github.com/Yuukiy/JavSP%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%9C%AC%E5%9C%B0%E5%88%AE%E5%89%8A%E7%9A%84%EF%BC%8Chttps://github.com/Yuukiy/JavSP/blob/master/core/avid.py%E8%BF%99%E4%BD%8D%E8%80%81%E5%93%A5%E8%BE%9B%E8%8B%A6%E6%95%B4%E7%9A%84%E6%AD%A3%E5%88%99%E3%80%82(%E6%89%8B%E5%8A%A8%E7%8B%97%E5%A4%B4))

这位大佬厉害呀，还统计出各种情况出现的概率
